name: Run Ansible Playbook

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the desired runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your desired Python version

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Create Amazon RDS  Playbook
        run: ansible/create-rds-db.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False  # Optional if host key checking needs to be disabled
