# 00_deploy_service.yaml
name: deploy_service

on:
  push:
    branches:
      - dev  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Use the desired Python version

    - name: Install Ansible and botocore
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        pip install boto3 botocore

    # - name: Install Botocore
    #   run: |
    #     pip install boto3 botocore

    - name: Run Ansible playbook
      env:
        AWS_ACCESS_KEY_ID: ${{ secret.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secret.AWS_SECRET_ACCESS_KEY }}
        RDS_DB_USERNAME: ${{ secret.RDS_DB_USERNAME }}
        RDS_DB_PASSWORD: ${{ secret.RDS_DB_PASSWORD }}



      run: |

      ansible-playbook -e "aws_access_key=$AWS_ACCESS_KEY_ID aws_secret_key=$AWS_SECRET_ACCESS_KEY username=$RDS_DB_USERNAME password=$RDS_DB_PASSWORD" ansible/create-rds-db.yaml
     

    # You can add more steps for notifications, testing, etc. after deployment
    # ansible-playbook -e "aws_access_key=$AWS_ACCESS_KEY_ID" -e "aws_secret_key=$AWS_SECRET_ACCESS_KEY" -e "username=$RDS_DB_USERNAME" -e password=$RDS_DB_PASSWORD" ansible/create-rds-db.yaml

