name: Ansible Amazon RDS Deployment

on:
  push:
    branches:
      - dev  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Use the desired Python version

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Install Botocore
      run: |
        pip install botocore

    - name: Run Ansible playbook
      run: ansible-playbook ansible/create-rds-db.yaml  # Adjust the playbook filename

    # You can add more steps for notifications, testing, etc. after deployment

